general.import = ["dracula.toml"]

[window]
decorations = "None"
opacity = 0.8
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10

[font]
size = 20

[cursor.style]
shape = "Block"
blinking = "Always"

[selection]
save_to_clipboard = true
