import = ["~/.config/alacritty/dracula.toml"]

[window]
decorations = "None"

[window.padding]
x = 10
y = 10

[font]
size = 12

[cursor.style]
shape = "Block"
blinking = "Always"

[selection]
save_to_clipboard = true
